# Generated by Django 4.1.1 on 2022-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('username', models.CharField(max_length=39, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('websiteURL', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('bio', models.CharField(max_length=160, null=True)),
                ('profilePictureURL', models.CharField(max_length=255, null=True)),
                ('followersCount', models.IntegerField(default=0)),
                ('repositoriesCount', models.IntegerField(default=0)),
                ('forksObtained', models.IntegerField(default=0)),
                ('starsObtained', models.IntegerField(default=0)),
                ('languageMostUsed', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
