# Generated by Django 4.1.1 on 2022-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='languageMostUsed',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
