# Generated by Django 4.1.1 on 2022-09-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_githubuser_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='profilePictureURL',
            new_name='avatarUrl',
        ),
        migrations.RenameField(
            model_name='githubuser',
            old_name='forksObtained',
            new_name='forkCount',
        ),
        migrations.RenameField(
            model_name='githubuser',
            old_name='languageMostUsed',
            new_name='mostUsedLanguage',
        ),
        migrations.RenameField(
            model_name='githubuser',
            old_name='starsObtained',
            new_name='stargazerCount',
        ),
        migrations.RenameField(
            model_name='githubuser',
            old_name='websiteURL',
            new_name='websiteUrl',
        ),
    ]
