# Generated by Django 4.1.1 on 2022-09-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_rename_profilepictureurl_githubuser_avatarurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='username',
            new_name='userName',
        ),
    ]
